# Generated by Django 2.1.1 on 2019-03-25 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_image', models.ImageField(upload_to='')),
                ('date_emotion', models.CharField(max_length=200, null=True)),
                ('date_name', models.CharField(max_length=200, null=True)),
                ('movie_suggestion_1', models.CharField(max_length=200, null=True)),
                ('movie_suggestion_2', models.CharField(max_length=200, null=True)),
                ('movie_suggestion_3', models.CharField(max_length=200, null=True)),
                ('movie_genre', models.CharField(max_length=200, null=True)),
                ('song_suggestion_1', models.CharField(max_length=200, null=True)),
                ('song_suggestion_2', models.CharField(max_length=200, null=True)),
                ('song_suggestion_3', models.CharField(max_length=200, null=True)),
                ('song_genre', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
