# Generated by Django 2.1.1 on 2019-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='date_emotion',
            new_name='emotion',
        ),
        migrations.RenameField(
            model_name='date',
            old_name='date_name',
            new_name='movie_path_1',
        ),
        migrations.RenameField(
            model_name='date',
            old_name='movie_genre',
            new_name='movie_path_2',
        ),
        migrations.RenameField(
            model_name='date',
            old_name='song_genre',
            new_name='movie_path_3',
        ),
        migrations.RemoveField(
            model_name='date',
            name='date_image',
        ),
        migrations.RemoveField(
            model_name='date',
            name='song_suggestion_1',
        ),
        migrations.RemoveField(
            model_name='date',
            name='song_suggestion_2',
        ),
        migrations.RemoveField(
            model_name='date',
            name='song_suggestion_3',
        ),
        migrations.AddField(
            model_name='date',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
